name: "Backend Tests"

on:
  pull_request:
    branches: [*]
  push:
    branches: [*]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./API

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@3
        with: 
          node-version: 18.x
        
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install 

      - name: Run tests
        run: pnpm test
        env: 
          DB_USERNAME = ${{ secrets.DB_USERNAME }}
          DB_PASSWORD = ${{ secrets.DB_PASSWORD }}
          DB_NAME = ${{ secrets.DB_NAME }}
          DB_URL = ${{ secrets.DB_URL }}     